export const themeStyle = {
    // 'primary-color': '#2f54eb',
    'blue-base': '#2f54eb',
    // 'tabs-highlight-color': '#2f54eb',
    // 'tabs-active-color': '#2f54eb',
    'border-color-base': '#e5e6eb',
    'orange-base': '#FF7D00',
    'radio-dot-color': '#2f54eb',
    'input-bg': 'rgb(242,243,245)',
    'select-background': 'rgb(242,243,245)',
    'picker-bg': 'rgb(242,243,245)',
    'picker-border-color': 'transparent',
    'input-border-color': 'transparent',
    'select-border-color': 'transparent',
    'form-error-input-bg': 'rgb(255,236,232)',
    'card-radius': '8px',
    'tooltip-distance': '8px',
    // 'steps-description-max-width': '180px'
    // 'input-hover-border-color': '#0262fd',
};
