#################################### SERVER ###############################
[server]
# The public facing domain name used to access server from a browser
domain = "0.0.0.0"
app_api_url = 'https://api.spotterio.com'

#################################### DATABASE ###############################
[database]
enable = false
[database.mysql]
database= 'gmesh'
host = 'localhost'
username = 'root'
password = '123456'


#################################### Nacos ################################
[nacos]
[nacos.config_client]
serverAddr = 'nacos-in.spotter.ink:80'
i18n_translation_group = 'I18N_TRANSLATION_GROUP'
vc_session_group = 'VC_SESSION_GROUP'
# 账号池的列表，新增账号需要手动同步账号的基础信息进入该 pool
vc_account_pool_data_id = 'vc_account_pool'

#################################### Client Monitor ######################################
[client_monitor]
enable = true
sdk_cdn_url = 'https://cdn-go.cn/aegis/aegis-sdk/latest/aegis.min.js'
# 上报 id
id='3og0EuLmgLod29713y'
# 接口测速
report_api_speed= true
# 静态资源测速
report_asset_speed= true
# spa 应用页面跳转的时候开启 pv 计算
spa=true



#################################### Auth ###############################
[auth]
# URL for allowed cors origin
allowed_cors_origin_urls = ['https://api.spotterio.com/auth']

[auth.oauth2]
lark_url="https://open.feishu.cn/open-apis/authen/v1/index?app_id=cli_a2b8615b7dfdd00b&redirect_uri=https%3A%2F%2Fapi.spotterio.com%2Fspotter-guard-web%2Fuser%2Ffeishu%2Fcallback&app=gmesh"
ding_url="https://login.dingtalk.com/oauth2/auth?redirect_uri=http%3A%2F%2Fapi.spotterio.com%2Fspotter-guard-web%2Fuser%2Fdingtalk%2Fcallback&response_type=code&client_id=dingc1u4qzssi1lcjd34&scope=openid&state=dddd&prompt=consent"

[bucket]
message_bucket_name = "message-prod-1303367458"
image_bucket_name = "ticket-prod-1303367458"
business_image_bucket_name = 'cooperation-prod-1303367458'
performance_bucket_name='performance-prod-1303367458'
