[server]
# The public facing domain name used to access server from a browser
domain = "0.0.0.0"
app_api_url = 'http://api.tst.spotterio.com'
bucket_name = "message-test-1303367458"

#################################### DATABASE ###############################
[database]
enable = false
[database.mysql]
database= 'gmesh'
host = 'localhost'
username = 'root'
password = '123456'

#################################### Auth ###############################
[auth]
[auth.oauth2]
lark_url="https://open.feishu.cn/open-apis/authen/v1/index?app_id=cli_a2b8615b7dfdd00b&redirect_uri=http%3A%2F%2Fapi.tst.spotterio.com%2Fspotter-guard-web%2Fuser%2Ffeishu%2Fcallback&app=gmesh"
ding_url="https://login.dingtalk.com/oauth2/auth?redirect_uri=http%3A%2F%2Fapi.tst.spotterio.com%2Fspotter-guard-web%2Fuser%2Fdingtalk%2Fcallback&response_type=code&client_id=dingc1u4qzssi1lcjd34&scope=openid&state=dddd&prompt=consent"

#################################### Nacos ################################
[nacos]
[nacos.config_client]
serverAddr = 'nacos.tst.spotter.ink:80'



#################################### Client Monitor ######################################
[client_monitor]
enable = true
sdk_cdn_url = 'https://cdn-go.cn/aegis/aegis-sdk/latest/aegis.min.js'
# 上报 id
id='Ll38zcjmVjKWgXXyj0'
# 接口测速
report_api_speed= true
# 静态资源测速
report_asset_speed= true
# spa 应用页面跳转的时候开启 pv 计算
spa=true

[bucket]
message_bucket_name = "message-test-1303367458"
image_bucket_name = "ticket-test-1303367458"
business_image_bucket_name = 'cooperation-test-1303367458'
performance_bucket_name='performance-test-1303367458'

